# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpeedMeter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpeedMeter

  target 'SpeedMeterTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'AWSAPIGateway', '~> 2.4.7'
  	pod 'AWSDynamoDB'
  end

  target 'SpeedMeterUITests' do
    # Pods for testing
  end

end
